# Map configuration
map:
  # Initial center of the map, as [longitude, latitude]
  # Default is Null Island
  center: [0, 0]
  # Initial zoom level of the map.
  # The minimum and maximum zoom levels are set automatically, depending on the annotation
  # Default is 2
  initialZoom: 2

# Score configuration
score:
  maxScore:
    # Smallest maximum score, for the smallest-scale warped maps (e.g. small countries)
    # Default is 10
    min: 10
    # Largest maximum score, for the largest-scale warped maps (e.g. city blocks)
    # Default is 100
    max: 100

  area:
    # Size of warped map in square meters to get the largest maximum score
    # Default is the size of an average city block in square meters
    min: 10000
    # Size of warped map in square meters to get the smallest maximum score
    # Default is the size of small country in square meters
    max: 25000000000

  time:
    # Time in seconds before timer starts to make maximum round score smaller.
    # Default is 5 seconds
    min: 8
    # Maximum duration of a round, in seconds.
    # Players get 0 points if they don't make a guess within this time.
    # Default is 300 seconds (5 minutes)
    max: 300

  # Score multiplier for displaying scores. 100 turns a score of 10 into 1000 points.
  # Default is 100
  displayScoreMultiplier: 100

# List of annotations used by Allmaps Arcade
# The list can contain single Annotations as well as AnnotationPages
annotationUrls:
  - https://annotations.allmaps.org/maps/a7b30d806ba1fb3c
  - https://annotations.allmaps.org/maps/7044e91ab1c516f6
  - https://annotations.allmaps.org/maps/34a3abc6a8034a6e
  - https://annotations.allmaps.org/maps/5bac051c791988f9
  - https://annotations.allmaps.org/maps/71bdb9db8c165c09
  - https://annotations.allmaps.org/maps/a097ce9981aee5fd
  - https://annotations.allmaps.org/maps/95eeba91177d2a1d
  - https://annotations.allmaps.org/maps/aaa0c42c86beda85
  - https://annotations.allmaps.org/maps/a0758d2723f14664
  - https://annotations.allmaps.org/maps/f72b9431c691a7c0
  - https://annotations.allmaps.org/maps/dd8af01a1789ed7e
  - https://annotations.allmaps.org/maps/603cadb0e08ac55b
  - https://annotations.allmaps.org/maps/68e20c1468b759b6
  - https://annotations.allmaps.org/maps/020d813d9fef01ef
  - https://annotations.allmaps.org/maps/cf4eb38cfd72a7e5
  - https://annotations.allmaps.org/maps/05e67c277e8c18f9
  - https://annotations.allmaps.org/maps/58acb78434c78969
  - https://annotations.allmaps.org/maps/21c8b7c9cc855ba4
  - https://annotations.allmaps.org/maps/c0c9199947c66bfc
  - https://annotations.allmaps.org/maps/79cf590481a14893
  - https://annotations.allmaps.org/maps/70361eb67f6d037c
  - https://annotations.allmaps.org/maps/2d49b3ecd1ba6346
  - https://annotations.allmaps.org/maps/ef7c54d692332d1f
  - https://annotations.allmaps.org/maps/d5692e535e71bb04
  - https://annotations.allmaps.org/maps/817f4ce19df88bc2
  - https://annotations.allmaps.org/maps/a71d7fcc2fc8eec9
  - https://annotations.allmaps.org/maps/045d14eea64fef36
  - https://annotations.allmaps.org/maps/affd9060f32a5673
  - https://annotations.allmaps.org/maps/fadff3df989fd81f
  - https://annotations.allmaps.org/maps/500fccb573a1ca22
  - https://annotations.allmaps.org/maps/213c50bee78244c4
  - https://annotations.allmaps.org/maps/e06f113b05a5fb22
  - https://annotations.allmaps.org/maps/d44d7b779ff9c15a
  - https://annotations.allmaps.org/maps/c2abd092a8c71881
  - https://annotations.allmaps.org/maps/fdf35e3f4e28cfd5
  - https://annotations.allmaps.org/maps/5fb6bf563d53980a
  - https://annotations.allmaps.org/maps/86b518e79fa0065b
  - https://annotations.allmaps.org/maps/a90e06678df811e3
  - https://annotations.allmaps.org/maps/e3bef2efe9455058
  - https://annotations.allmaps.org/maps/7944edc750d6b8b1
  - https://annotations.allmaps.org/maps/314261dbbff9caa6
  - https://annotations.allmaps.org/maps/91a6c9f43fcd217d
  - https://annotations.allmaps.org/maps/b6ad81e345d93472
  - https://annotations.allmaps.org/maps/b776fbf17098efb5
  - https://annotations.allmaps.org/maps/573c3f130f91839c
  - https://annotations.allmaps.org/maps/2f179ee583839b06
  - https://annotations.allmaps.org/maps/d68d99d70f21a1a8
  - https://annotations.allmaps.org/maps/5aa3ce47b380271b
  - https://annotations.allmaps.org/maps/8195d6b308dec982
  - https://annotations.allmaps.org/maps/28815b833aa39437
  - https://annotations.allmaps.org/maps/9aab3ddc83688f47
  - https://annotations.allmaps.org/maps/fc43e95eb69ca923
  - https://annotations.allmaps.org/maps/7a5b1693efb172e3
  - https://annotations.allmaps.org/maps/b2656975ffa5548c
  - https://annotations.allmaps.org/maps/6bcd681704f3fb4c
  - https://annotations.allmaps.org/maps/af416a6bddbfdfff
  - https://annotations.allmaps.org/maps/43799e41be4cc421
  - https://annotations.allmaps.org/maps/dc060d1817f5fc35
  - https://annotations.allmaps.org/maps/268c827143e7e571
  - https://annotations.allmaps.org/maps/2b68e3bb90ecd68d
  - https://annotations.allmaps.org/maps/da481b40f7818a8d
  - https://annotations.allmaps.org/maps/c171c9026b842681
  - https://annotations.allmaps.org/maps/aab223f037706c25
  - https://annotations.allmaps.org/maps/877d996668e83e14
  - https://annotations.allmaps.org/maps/1dfe35b95d261d2f
  - https://annotations.allmaps.org/maps/699016d82bc650b6
  - https://annotations.allmaps.org/maps/057658ec63de7785
  - https://annotations.allmaps.org/maps/096f57b5ff35b3eb
  - https://annotations.allmaps.org/maps/aa50ea6e3cffda6a
  - https://annotations.allmaps.org/maps/24e76fcb71df73db
  - https://annotations.allmaps.org/maps/3ccb157b909911f9
  - https://annotations.allmaps.org/maps/e16dd2a24cf0e185
  - https://annotations.allmaps.org/maps/5d5eeb9904fc008a
  - https://annotations.allmaps.org/maps/a9dad12e36b2af79
  - https://annotations.allmaps.org/maps/1dc2da63239b73ee
  - https://annotations.allmaps.org/maps/db5ae572068eefe9
  - https://annotations.allmaps.org/maps/d96aad0a7632a06e
  - https://annotations.allmaps.org/maps/814e150e26c93015
  - https://annotations.allmaps.org/maps/dd689913d12a4f61
  - https://annotations.allmaps.org/maps/c519cc410b20dd22
  - https://annotations.allmaps.org/maps/ca4a15bc7bf94be7
  - https://annotations.allmaps.org/maps/af527883a4caab60
  - https://annotations.allmaps.org/maps/8253098302539be3
  - https://annotations.allmaps.org/maps/669853ac9c27c077
  - https://annotations.allmaps.org/maps/e6f81255a5bcdc32
  - https://annotations.allmaps.org/maps/747f9e3cf0a61f16
  - https://annotations.allmaps.org/maps/5b8d0cb0d17315fb
  - https://annotations.allmaps.org/maps/b52190ae77274761
  - https://annotations.allmaps.org/maps/89b9318392415f15
  - https://annotations.allmaps.org/maps/ade1baa96e5875b2
  - https://annotations.allmaps.org/maps/39bc721e930d14c4
  - https://annotations.allmaps.org/maps/316582dfaa802109
  - https://annotations.allmaps.org/maps/881bd60c8599b84d
  - https://annotations.allmaps.org/maps/adc143cd3b1eab0a
  - https://annotations.allmaps.org/maps/5032ea7bf0cf1892
  - https://annotations.allmaps.org/maps/c459efc4df055bda
  - https://annotations.allmaps.org/maps/f09b39b5a143c942
  - https://annotations.allmaps.org/maps/b364a1fd6f97c466
  - https://annotations.allmaps.org/maps/f1434d4efbc1f61e
  - https://annotations.allmaps.org/maps/c76e9e48783296ed
  - https://annotations.allmaps.org/maps/d3a60841d0538b47
  - https://annotations.allmaps.org/maps/1bbdf07d8f9ddbb6
  - https://annotations.allmaps.org/maps/49c2aff054d984aa
  - https://annotations.allmaps.org/maps/6c2de861a9dea031
  - https://annotations.allmaps.org/maps/70256512530afcd6
  - https://annotations.allmaps.org/maps/3dfae7af7473abef
  - https://annotations.allmaps.org/maps/36d7f618a2eb0fbd
  - https://annotations.allmaps.org/maps/8dedb654a58cce3a
  - https://annotations.allmaps.org/maps/56008f9f7b717935
  - https://annotations.allmaps.org/maps/f6de62473a7b26c0
  - https://annotations.allmaps.org/maps/d370cda1dc759b2f
  - https://annotations.allmaps.org/maps/6ef54bd1ead27eb9
  - https://annotations.allmaps.org/maps/96fba33829b81357
  - https://annotations.allmaps.org/maps/398e502a2d9b5e6d
  - https://annotations.allmaps.org/maps/ef32d2a49cacfd40
  - https://annotations.allmaps.org/maps/d732b818148748b9
  - https://annotations.allmaps.org/maps/613eea28266438ef
  - https://annotations.allmaps.org/maps/68569f04b4240792
  - https://annotations.allmaps.org/maps/ce04e498f9d5cc12
  - https://annotations.allmaps.org/maps/6eff271d3445ddd0
  - https://annotations.allmaps.org/maps/350ae1a417eb6c9c
  - https://annotations.allmaps.org/maps/d0610493306b70da
  - https://annotations.allmaps.org/maps/2d3cd38313d655a4
  - https://annotations.allmaps.org/maps/c264500d8769ba31
  - https://annotations.allmaps.org/maps/c3684641fa73f433
  - https://annotations.allmaps.org/maps/372c09b3e1e896dd
  - https://annotations.allmaps.org/maps/6483574616817536
  - https://annotations.allmaps.org/maps/453c8908d3ba052c
  - https://annotations.allmaps.org/maps/e5c32c229a53f00d
  - https://annotations.allmaps.org/maps/451dd758ef59d111
  - https://annotations.allmaps.org/maps/8db30930964884a9
  - https://annotations.allmaps.org/maps/c84765758b08eb1f
  - https://annotations.allmaps.org/maps/9bc52e2056186193
  - https://annotations.allmaps.org/maps/c21bc266fefa0982
  - https://annotations.allmaps.org/maps/1d732e22331a59c1
  - https://annotations.allmaps.org/maps/aae9feb5043cba65
  - https://annotations.allmaps.org/manifests/ea216d5d18cd7451
  - https://annotations.allmaps.org/images/8d4493aaa4122c43
  - https://annotations.allmaps.org/images/03ed279474d44844
  - https://annotations.allmaps.org/images/f3c00c845d32346b
  - https://annotations.allmaps.org/manifests/cb88af910733e2bd
  - https://annotations.allmaps.org/images/51646a41c7f9ea75
  - https://annotations.allmaps.org/maps/3075257ad286a088
  - https://annotations.allmaps.org/maps/f17e60c96e6d681f
  - https://annotations.allmaps.org/maps/ae7b88ed649bb40e
  - https://annotations.allmaps.org/maps/12b64b5d8a865a2a
  - https://annotations.allmaps.org/maps/8884657dec4a6530
  - https://annotations.allmaps.org/maps/18cee8330b3a1a3f
  - https://annotations.allmaps.org/maps/34643c2fde5d1e93
  - https://annotations.allmaps.org/maps/233794dc88ae7242
  - https://annotations.allmaps.org/maps/2cc8355ed13d0ad3
  - https://annotations.allmaps.org/maps/6c4f022c239a565e
  - https://annotations.allmaps.org/maps/ad870063d3995022
  - https://annotations.allmaps.org/maps/823477e46012e947
  - https://annotations.allmaps.org/maps/0431887a9d208417
  - https://annotations.allmaps.org/maps/73e0271f44cc8838
  - https://annotations.allmaps.org/maps/2667ad4b03382f79
  - https://annotations.allmaps.org/maps/b22fd81e1c13e4d7
  - https://annotations.allmaps.org/maps/e5a8225f83f81189
  - https://annotations.allmaps.org/maps/83ead11405073450
  - https://annotations.allmaps.org/maps/3c9f3520b630cb76
  - https://annotations.allmaps.org/maps/ae2ef16e7859f814
  - https://annotations.allmaps.org/maps/0994509a521dab49
  - https://annotations.allmaps.org/maps/8e70dcbe4ce37ad9
  - https://annotations.allmaps.org/maps/a79aa30b9df3e3b5
  - https://annotations.allmaps.org/maps/8af5fb867819e6f3
  - https://annotations.allmaps.org/maps/c82a1b02d56e1e2c
  - https://annotations.allmaps.org/maps/ae7db1c765f47416
  - https://annotations.allmaps.org/maps/6e40bd9829b56fe7
  - https://annotations.allmaps.org/maps/572438e094bf3935
  - https://annotations.allmaps.org/maps/b2802520064ac96d
  - https://annotations.allmaps.org/maps/c629b1caafb10013
  - https://annotations.allmaps.org/maps/8f86e07e47c53f1e
  - https://annotations.allmaps.org/maps/c477b3f666146611
  - https://annotations.allmaps.org/maps/a6388d364c56d24d
  - https://annotations.allmaps.org/maps/878536ba2ed87eb4
  - https://annotations.allmaps.org/maps/3794cb189f90a93f
  - https://annotations.allmaps.org/maps/1cef48cbc222ea91
  - https://annotations.allmaps.org/maps/47a61b59e6ec6002
  - https://annotations.allmaps.org/images/d216a04c93280f18
  - https://annotations.allmaps.org/maps/76d9a86a84f9f7b6
  - https://annotations.allmaps.org/maps/a7081c4f92e9287c
  - https://annotations.allmaps.org/maps/f26954c7c075bf97
  - https://annotations.allmaps.org/maps/9b4fe711438e9c2e
  - https://annotations.allmaps.org/maps/a2ccad41b422eabf
  - https://annotations.allmaps.org/maps/036509c0a91dd48d
  - https://annotations.allmaps.org/maps/13d5de6e70269314
  - https://annotations.allmaps.org/maps/8a6d1e0597b8a5ba
  - https://annotations.allmaps.org/maps/31b7e8a4874885a8
  - https://annotations.allmaps.org/maps/97598dc55df6afea
  - https://annotations.allmaps.org/maps/a2ccad41b422eabf
  - https://annotations.allmaps.org/maps/1f0b6bda18465004
  - https://annotations.allmaps.org/images/aab5f7eb40d1dc3d
  - https://annotations.allmaps.org/maps/b84eeaabaa842fa4
  - https://annotations.allmaps.org/images/d82772a16e62c0a3
  - https://annotations.allmaps.org/images/bf0efd29142526cd
  - https://annotations.allmaps.org/images/32c95c08b3b84d95
  - https://annotations.allmaps.org/images/7880aa775015f537
  - https://annotations.allmaps.org/images/43bd1b3612cb8a96
  - https://annotations.allmaps.org/images/6c0a62f6710a2c58
  - https://annotations.allmaps.org/images/474899d788deb15a
  - https://annotations.allmaps.org/images/f80b892e50e57746
  - https://annotations.allmaps.org/images/40948b24db7cdbd3
  - https://annotations.allmaps.org/images/53bd2314d7afb637
  - https://annotations.allmaps.org/images/bb27169601cd8fb2
  - https://annotations.allmaps.org/images/19cfb81eba25f36b
  - https://annotations.allmaps.org/images/cc9afdcfff104240
  - https://annotations.allmaps.org/images/6da8bc7b86fb81a0
  - https://annotations.allmaps.org/images/f2695cbfdfa6e36c
  - https://annotations.allmaps.org/images/52d10eb60c40f741
  - https://annotations.allmaps.org/images/9a9e3422073c4db7
  - https://annotations.allmaps.org/images/379253fdf2ff33e0
  - https://annotations.allmaps.org/images/0be1d1c06f55b57c
  - https://annotations.allmaps.org/images/aa029df38795f9ae
  - https://annotations.allmaps.org/images/2270d4b4da0f5dc2
  - https://annotations.allmaps.org/images/1486303d0ee0f651
  - https://annotations.allmaps.org/images/7e7360639d54ec33
  - https://annotations.allmaps.org/images/19ce1a248d6f41e5
  - https://annotations.allmaps.org/images/1755ad477e863d8d
  - https://annotations.allmaps.org/images/ecbc1c39d58fae0e
  - https://annotations.allmaps.org/images/ac648f05a225dc74
